linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gosec:
    excludes:
      - G104
