apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-vpc-file-pool-csi-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-vpc-file-pool-csi-node
  namespace: kube-system
