//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- AccessorZone ---

func (in *AccessorZone) DeepCopyInto(out *AccessorZone) {
	*out = *in
}

func (in *AccessorZone) DeepCopy() *AccessorZone {
	if in == nil {
		return nil
	}
	out := new(AccessorZone)
	in.DeepCopyInto(out)
	return out
}

// --- ZoneMountTarget ---

func (in *ZoneMountTarget) DeepCopyInto(out *ZoneMountTarget) {
	*out = *in
}

func (in *ZoneMountTarget) DeepCopy() *ZoneMountTarget {
	if in == nil {
		return nil
	}
	out := new(ZoneMountTarget)
	in.DeepCopyInto(out)
	return out
}

// --- ShareTier ---

func (in *ShareTier) DeepCopyInto(out *ShareTier) {
	*out = *in
	if in.IOPS != nil {
		in, out := &in.IOPS, &out.IOPS
		*out = new(int64)
		**out = **in
	}
}

func (in *ShareTier) DeepCopy() *ShareTier {
	if in == nil {
		return nil
	}
	out := new(ShareTier)
	in.DeepCopyInto(out)
	return out
}

// --- ShareDrainStatus ---

func (in *ShareDrainStatus) DeepCopyInto(out *ShareDrainStatus) {
	*out = *in
	if in.DrainStartedAt != nil {
		in, out := &in.DrainStartedAt, &out.DrainStartedAt
		*out = (*in).DeepCopy()
	}
}

func (in *ShareDrainStatus) DeepCopy() *ShareDrainStatus {
	if in == nil {
		return nil
	}
	out := new(ShareDrainStatus)
	in.DeepCopyInto(out)
	return out
}

// --- PoolShareStatus ---

func (in *PoolShareStatus) DeepCopyInto(out *PoolShareStatus) {
	*out = *in
	if in.MountTargets != nil {
		in, out := &in.MountTargets, &out.MountTargets
		*out = make([]ZoneMountTarget, len(*in))
		copy(*out, *in)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

func (in *PoolShareStatus) DeepCopy() *PoolShareStatus {
	if in == nil {
		return nil
	}
	out := new(PoolShareStatus)
	in.DeepCopyInto(out)
	return out
}

// --- FileSharePoolSpec ---

func (in *FileSharePoolSpec) DeepCopyInto(out *FileSharePoolSpec) {
	*out = *in
	if in.IOPS != nil {
		in, out := &in.IOPS, &out.IOPS
		*out = new(int64)
		**out = **in
	}
	if in.DefaultUID != nil {
		in, out := &in.DefaultUID, &out.DefaultUID
		*out = new(int64)
		**out = **in
	}
	if in.DefaultGID != nil {
		in, out := &in.DefaultGID, &out.DefaultGID
		*out = new(int64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MountOptions != nil {
		in, out := &in.MountOptions, &out.MountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccessorZones != nil {
		in, out := &in.AccessorZones, &out.AccessorZones
		*out = make([]AccessorZone, len(*in))
		copy(*out, *in)
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]ShareTier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DrainShares != nil {
		in, out := &in.DrainShares, &out.DrainShares
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *FileSharePoolSpec) DeepCopy() *FileSharePoolSpec {
	if in == nil {
		return nil
	}
	out := new(FileSharePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// --- FileSharePoolStatus ---

func (in *FileSharePoolStatus) DeepCopyInto(out *FileSharePoolStatus) {
	*out = *in
	if in.Shares != nil {
		in, out := &in.Shares, &out.Shares
		*out = make([]PoolShareStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DrainStatus != nil {
		in, out := &in.DrainStatus, &out.DrainStatus
		*out = make([]ShareDrainStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

func (in *FileSharePoolStatus) DeepCopy() *FileSharePoolStatus {
	if in == nil {
		return nil
	}
	out := new(FileSharePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// --- FileSharePool ---

func (in *FileSharePool) DeepCopyInto(out *FileSharePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *FileSharePool) DeepCopy() *FileSharePool {
	if in == nil {
		return nil
	}
	out := new(FileSharePool)
	in.DeepCopyInto(out)
	return out
}

func (in *FileSharePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- FileSharePoolList ---

func (in *FileSharePoolList) DeepCopyInto(out *FileSharePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FileSharePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *FileSharePoolList) DeepCopy() *FileSharePoolList {
	if in == nil {
		return nil
	}
	out := new(FileSharePoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *FileSharePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SnapshotSpec ---

func (in *SnapshotSpec) DeepCopyInto(out *SnapshotSpec) {
	*out = *in
}

func (in *SnapshotSpec) DeepCopy() *SnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// --- SnapshotStatus ---

func (in *SnapshotStatus) DeepCopyInto(out *SnapshotStatus) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

func (in *SnapshotStatus) DeepCopy() *SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// --- Snapshot ---

func (in *Snapshot) DeepCopyInto(out *Snapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Snapshot) DeepCopy() *Snapshot {
	if in == nil {
		return nil
	}
	out := new(Snapshot)
	in.DeepCopyInto(out)
	return out
}

func (in *Snapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SnapshotList ---

func (in *SnapshotList) DeepCopyInto(out *SnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Snapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SnapshotList) DeepCopy() *SnapshotList {
	if in == nil {
		return nil
	}
	out := new(SnapshotList)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- CloneProgress ---

func (in *CloneProgress) DeepCopyInto(out *CloneProgress) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

func (in *CloneProgress) DeepCopy() *CloneProgress {
	if in == nil {
		return nil
	}
	out := new(CloneProgress)
	in.DeepCopyInto(out)
	return out
}

// --- SubVolumeSpec ---

func (in *SubVolumeSpec) DeepCopyInto(out *SubVolumeSpec) {
	*out = *in
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(int64)
		**out = **in
	}
	if in.GID != nil {
		in, out := &in.GID, &out.GID
		*out = new(int64)
		**out = **in
	}
}

func (in *SubVolumeSpec) DeepCopy() *SubVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(SubVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// --- SubVolumeStatus ---

func (in *SubVolumeStatus) DeepCopyInto(out *SubVolumeStatus) {
	*out = *in
	if in.ActualUsageBytes != nil {
		in, out := &in.ActualUsageBytes, &out.ActualUsageBytes
		*out = new(int64)
		**out = **in
	}
	if in.LastUsageCheck != nil {
		in, out := &in.LastUsageCheck, &out.LastUsageCheck
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CloneProgress != nil {
		in, out := &in.CloneProgress, &out.CloneProgress
		*out = new(CloneProgress)
		(*in).DeepCopyInto(*out)
	}
}

func (in *SubVolumeStatus) DeepCopy() *SubVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(SubVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// --- SubVolume ---

func (in *SubVolume) DeepCopyInto(out *SubVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SubVolume) DeepCopy() *SubVolume {
	if in == nil {
		return nil
	}
	out := new(SubVolume)
	in.DeepCopyInto(out)
	return out
}

func (in *SubVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SubVolumeList ---

func (in *SubVolumeList) DeepCopyInto(out *SubVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SubVolumeList) DeepCopy() *SubVolumeList {
	if in == nil {
		return nil
	}
	out := new(SubVolumeList)
	in.DeepCopyInto(out)
	return out
}

func (in *SubVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- GroupSnapshotMember ---

func (in *GroupSnapshotMember) DeepCopyInto(out *GroupSnapshotMember) {
	*out = *in
}

func (in *GroupSnapshotMember) DeepCopy() *GroupSnapshotMember {
	if in == nil {
		return nil
	}
	out := new(GroupSnapshotMember)
	in.DeepCopyInto(out)
	return out
}

// --- VolumeGroupSnapshotSpec ---

func (in *VolumeGroupSnapshotSpec) DeepCopyInto(out *VolumeGroupSnapshotSpec) {
	*out = *in
	if in.SourcePVCs != nil {
		in, out := &in.SourcePVCs, &out.SourcePVCs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CopyOrder != nil {
		in, out := &in.CopyOrder, &out.CopyOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *VolumeGroupSnapshotSpec) DeepCopy() *VolumeGroupSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeGroupSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// --- VolumeGroupSnapshotStatus ---

func (in *VolumeGroupSnapshotStatus) DeepCopyInto(out *VolumeGroupSnapshotStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]GroupSnapshotMember, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

func (in *VolumeGroupSnapshotStatus) DeepCopy() *VolumeGroupSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeGroupSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// --- VolumeGroupSnapshot ---

func (in *VolumeGroupSnapshot) DeepCopyInto(out *VolumeGroupSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VolumeGroupSnapshot) DeepCopy() *VolumeGroupSnapshot {
	if in == nil {
		return nil
	}
	out := new(VolumeGroupSnapshot)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeGroupSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VolumeGroupSnapshotList ---

func (in *VolumeGroupSnapshotList) DeepCopyInto(out *VolumeGroupSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeGroupSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VolumeGroupSnapshotList) DeepCopy() *VolumeGroupSnapshotList {
	if in == nil {
		return nil
	}
	out := new(VolumeGroupSnapshotList)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeGroupSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
