apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: vpc-file-pool.csi.ibm.io
  labels:
    {{- include "ibm-vpc-file-pool-csi.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
  storageCapacity: false
