apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-vpc-file-pool-csi.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibm-vpc-file-pool-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "ibm-vpc-file-pool-csi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
