{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ibm-vpc-file-pool-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibm-vpc-file-pool-csi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ibm-vpc-file-pool-csi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
