apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibm-vpc-file-pool-csi.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibm-vpc-file-pool-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibm-vpc-file-pool-csi.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibm-vpc-file-pool-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
  {{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
  {{- end }}
