{{- if .Values.volumeSnapshotClass.create }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.volumeSnapshotClass.name }}
  labels:
    {{- include "ibm-vpc-file-pool-csi.labels" . | nindent 4 }}
driver: vpc-file-pool.csi.ibm.io
deletionPolicy: {{ .Values.volumeSnapshotClass.deletionPolicy }}
{{- end }}
